import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Store from "./components/Store";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kristi - All in one Fashion Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} relative ${geistMono.variable} antialiased`}
      >
        <Store children={children}/>
      </body>
    </html>
  );
}
