import { Montserrat } from "next/font/google";
import "./globals.css";
import Store from "./components/Store";


const montserrat = Montserrat({
  weight:['100','200','300','400','500','600','700','800','900'],
  subsets: ['latin'],
})

export const metadata = {
  title: "Kristi - All in one Fashion Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} relative antialiased`}
      >
        <Store children={children}/>
      </body>
    </html>
  );
}
